# Generated by Django 3.0.8 on 2020-07-14 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0006_auto_20200714_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 14, 2, 56, 40, 227341)),
        ),
    ]
